version: "3.9"
services:
  my-map-world:
    build:
      context: ./my-map-world
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./my-map-world:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin-orbidi:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5000:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - orbidi_network
  nocodb-odrbidi:
    image: nocodb/nocodb
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/cyc
    volumes:
      - ./nocodb_data:/usr/app/data
    networks:
      - orbidi_network
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - my-map-world
    networks:
      - orbidi_network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./app:/app
    restart: on-failure
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:8000/api/v1/healthcheck || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:latest
    command: redis-server --requirepass 63709598
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=63709598
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - -a
        - "63709598"
        - ping
      interval: 30s
      timeout: 10s
      retries: 3
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_orbidi
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    networks:
      - orbidi_network  
  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - 5010:80
    networks:
      - orbidi_network
networks:
  orbidi_network: 
volumes:
  db_data:
  pgadmin_data: 
  ollama_data: 
  nocodb_data: 

