version: "3.9"
services:
  my-map-world:
    image: your-registry/my-map-world:latest
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin-orbidi:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5000:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - orbidi_network

  app:
    image: your-registry/app:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: on-failure
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:8000/api/v1/healthcheck || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    command: redis-server --requirepass 63709598
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=63709598
    networks:
      - orbidi_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - -a
        - "63709598"
        - ping
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  orbidi_network:

volumes:
  db_data:
  pgadmin_data:
