version: "3.9"
services:
  my-map-world:
    build:
      context: ./my-map-world
    environment:
      - NODE_ENV=test
    volumes:
      - ./my-map-world:/app
      - /app/node_modules
      - /app/.next
    networks:
      - orbidi_network

  # pgadmin-orbidi-test:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - db
  #   volumes:
  #     - pgadmin_data_test:/var/lib/pgadmin
  #   networks:
  #     - orbidi_network

  app-test:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - 8002:8002
    depends_on:
      - db-test
    environment:
      DB_HOST: 
      DB_PORT: "5433"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ENVIRONMENT: test
    volumes:
      - ./app:/app
    restart: on-failure
    networks:
      - orbidi_network

  db-test:
    image: postgres:latest
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: db-test
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - orbidi_network

  # redis:
  #   image: redis:latest
  #   command: redis-server --requirepass 63709598
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - REDIS_PASSWORD=63709598
  #   networks:
  #     - orbidi_network

networks:
  orbidi_network:

volumes:
  db_data:
